package com.dash.travel.data.ai

import com.dash.travel.data.model.GeneratePlanResponse
import com.dash.travel.data.model.GeneratedItem

class OnDeviceGeminiStrategy : AIStrategy {
    
    // Simulate SDK availability check
    override suspend fun isAvailable(): Boolean {
        // Force false to trial cloud strategy during development/testing
        // even on Pixel devices that would normally support the simulation.
        return false
        /*
        val deviceModel = android.os.Build.MODEL
        // Check for "Pixel 10 Pro" (Simulated future device) or Pixel 8/9
        return deviceModel.contains("Pixel 10", ignoreCase = true) || 
               deviceModel.contains("Pixel 9", ignoreCase = true) ||
               deviceModel.contains("Pixel 8", ignoreCase = true)
        */
    }

    override suspend fun generatePlan(
        prompt: String,
        tripId: String?,
        preferences: UserPreferences?
    ): Result<GeneratePlanResponse> {
        return try {
            // Simulating On-Device Generation latency (faster than cloud)
            kotlinx.coroutines.delay(500)
            
            Result.success(
                GeneratePlanResponse(
                    success = true,
                    items = listOf(
                        GeneratedItem(
                            type = "activity",
                            title = "On-Device: Kinkaku-ji",
                            description = "Golden Pavilion. (Generated by Gemini Nano on ${android.os.Build.MODEL})",
                            locationName = "Kyoto, Japan",
                            estimatedCost = 400.0, // Cheap/Free
                            currency = "JPY"
                        ),
                        GeneratedItem(
                            type = "eat",
                            title = "On-Device: Ramen Sen-no-Kaze",
                            description = "Popular ramen spot. (Generated locally)",
                            locationName = "Kyoto, Japan",
                            estimatedCost = 1200.0,
                            currency = "JPY"
                        )
                    ),
                    summary = "Plan generated via OnDeviceGeminiStrategy"
                )
            )
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
}
